### ISSUE TITLE
Singularity shell interpreter: sourcing script from PATH

### ISSUE THREAD

**Issue by cclerget** [singularityware/singularity#6220]
Since the introduction of https://github.com/hpcng/singularity/pull/5028 in 3.6, sourcing a script based on PATH wasn't implemented leading to user issues like reported [here](https://groups.google.com/u/1/a/lbl.gov/g/singularity/c/bG19UJt0Le8)

**Comment by manuelschwarze** [comment]
Thanks a lot for addressing this issue. I will be happy to test a fix. I did not find the time yet to patch our Singularity containers, which is a good thing, because it won't be necessary if your fix is working.

**Comment by gmkurtzer** [comment]
Sorry we missed this @manuelschwarze! I got your comment on the "Singularity Future" poll about it so I'm glad to see things getting resolved.

**Comment by manuelschwarze** [comment]
Hi @cclerget , I saw it was addressed upstream in another PR than listed here. Two questions:
1. Will this fix be back-ported to all Singularity versions starting with 3.6, which broke that behavior?
2. How can I test the fix with an RPM package for CentOS 7.9?

**Comment by cclerget** [comment]
Hey @manuelschwarze ,

1. No it won't be backported to previous broken versions.
2. This is actually an issue for us to integrate the fix #6221 as it require go 1.16 and EPEL is providing only go 1.15, sorry but for the moment the only way to test it is to compile it yourself from the PR branch https://github.com/hpcng/singularity/pull/6221 by using go 1.16

**Comment by manuelschwarze** [comment]
Hi @cclerget, 
I just discussed the testing with my NIBR colleague who usually builds our Singularity RPM packages for NIBR. I would like to send him the exact GitHub branch so that he can use that to build a special temporary package for me for testing this fix. Could you please paste the URL that we should use for accessing the source code? It should be **as close as possible to the normal release code**, so that our build process is not choking. Beside that, when can we expect that the fix is being released? What version will it be in?

**Comment by cclerget** [comment]
Hi @manuelschwarze , you can grab it from the master branch, the fix have been included along with a fix from @DrDaveD for building RPM, so you should be able to generate the RPM directly from the master branch with instructions here https://github.com/hpcng/singularity/blob/master/INSTALL.md#building--installing-from-an-rpm

**Comment by DrDaveD** [comment]
This will be in the 3.9.0 release.  We do not have an estimated date for that at this point.

**Comment by DrDaveD** [comment]
This is getting backported to 3.8.5 as a side effect of #6305.
