### ISSUE TITLE
Singularity 3.8.6 .deb -- Python 2 dependency?

### ISSUE THREAD

**Issue by kwilczek** [singularityware/singularity#6407]
I tried to install the new `.deb` version under Debian 11 "Bullseye", but unfortunately the installation failed because of `python` dependency. 

```sh
The following packages have unmet dependencies:
 singularity-container : Depends: python but it is not installable
```

Running `dpkg-deb --info singularity-container_3.8.6_amd64.deb` gives:

```sh
Depends: libc6 (>= 2.14), libseccomp2 (>= 2.4.1), python, squashfs-tools
```

This `python` dependency is ambiguous. Apart from installing on Debian 11 I tried to install the package on Ubuntu 20.04, where it succeded, but pulled `python2` as a dependency. Is Python 2 a real dependency or is this an ambigiuous `python` problem?

**Comment by DrDaveD** [comment]
Since you haven't submitted an apptainer issue yet I'll just go ahead and answer on this closed ticket.

It turns out that python isn't actually used, and it has been removed as a dependency in the release-3.8 branch but we haven't cut a new release with it.  You can work around it with the 3.8.6 package by just installing python by hand.
